dataset:
  root: G:/Projects/img2brep/data/single_image_diffusion

trainer:
  stage: 0

  learning_rate: 1e-4
  gpu: 1
  num_worker: 0
  spawn: false
  batch_size: 1
  checkpoint_autoencoder:
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 1
  accelerator: "32-true"

model:
  focal_alpha: 0.75

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled