dataset:
  root: /mnt/d/meshgpt/0planar_shapes_100
  dataset_name: ABC
  overfit: false
  tokenized_batch_size: 16

trainer:
  learning_rate: 1e-4
  gpu: [0,1,2,3,4,5,6,7,8,9]
  num_worker: 8

  vis_recon_faces: true
  train_transformer: true
  condition_on_text: true

  num_samples: -1
  batch_size: 16

  spawn: false
  checkpoint_autoencoder: /root/workspace/python/src/img2brep/meshgpt/tb_logs/autoencoder/version_1/checkpoints/epoch=566-step=2835.ckpt
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 100
  accelerator: "32-true"

model:
  model_name: PC_model
  with_bn: true
  channels: 3
  output_channels: 1
  need_normalize: true
  voxelize_res: 256
  test_threshold: 0.5
  focal_alpha: 0.75

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled