name: img2brep
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libiconv=1.17
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - pyg=2.5.2=py310_torch_2.0.0_cu118
  - python=3.10.14
  - pythonocc-core=7.7.2
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0=cuda
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pip:
      - -f https://data.pyg.org/whl/torch-2.0.1+cu118.html
      - hydra-core==1.3.2
      - igraph==0.11.4
      - lightning-utilities==0.11.2
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - open3d==0.18.0
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - pandas==2.2.2
      - plotly==5.20.0
      - plyfile==1.0.3
      - pymcubes==0.1.4
      - pytorch-lightning==2.2.2
      - pyyaml==6.0.1
      - ray==2.10.0
      - scikit-image==0.23.1
      - shapely==2.0.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - torch-cluster==1.6.3+pt20cu118
      - torch-scatter==2.1.2+pt20cu118
      - torch-sparse==0.6.18+pt20cu118
      - torch-spline-conv==1.2.2+pt20cu118
      - torchmetrics==1.3.2
      - trimesh==4.3.0
      - einops==0.7.0
      - h5py==3.11.0
      - denoising-diffusion-pytorch==1.11.0
      - diffusers==0.27.2
      - einops==0.7.0
      - x-transformers==1.27.16
      - vector_quantize_pytorch==1.14.7