dataset:
  scene_boundary: [-50, -50, -10, 250, 200, 60]
#  colmap_dir: "C:/DATASET/Test_imgs2_colmap_neural/sparse_align"
  colmap_dir: "d:/Projects/NeuralRecon/Test_data/OBL_L7/Test_imgs2_colmap_neural/sparse_align"
  img_size: [6000,4000]
  num_sample: 1e8
  resample_after_n_epoches: 30
  target_img: ['6h00277','6h00278','6h00279','6h00280']

trainer:
  check_val_every_n_epoch: 30
  learning_rate: 1e-4
  gpu: 1
  num_worker: 2

#  batch_size: 4096
  batch_size: 262144
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false

  output: output/neural_recon/img_nif_log

model:
  model_name: Uncertainty_Modeling
  marching_cube_resolution: 128

hydra:
  run:
    dir: .
  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled