dataset:
  scene_boundary: [-1.5, -1.5, -1.5, 1.5, 1.5, 1.5]
  colmap_dir: "d:/Projects/NeuralRecon/Test_data/OBL_L7/Test_imgs2_colmap_neural/sparse_align"
  only_train_target: 1522

trainer:
  check_val_every_n_epoch: 1
  learning_rate: 1e-5
  gpu: 1
  num_worker: 0
  batch_size: 1
  auto_lr_find: false
#  resume_from_checkpoint: outputs/2023_03_28_15_25_48/lightning_logs/version_0/checkpoints/epoch=12999-step=13000.ckpt
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false
  output: imgs_log

  loss_weight: [1, 0.01, 0] # similarity_weight, normal_weight, normalization_weight
  num_sample: 1000 # number of gaussian sample
#  img_model: "model" # ["model", "sample"]
  img_model: "sample" # ["model", "sample"]


model:
  model_name: Uncertainty_Modeling
  marching_cube_resolution: 128
  img_model_dir: "output/neural_recon/ngp_models"

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled