dataset:
  img_size: [6000,4000]
  num_sample: 1e8 # Not used
  target_img: ['6h00277']

trainer:
  max_epoch: 5000
  check_val_every_n_epoch: 10
  batch_size: 48000
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0
  resume_from_checkpoint:
  output: output/neural_recon/img_nif_log

model:
  model_name: Image_model

hydra:
  run:
    dir: .
  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled