dataset:
  scene_boundary: [-50, -50, -10, 250, 200, 60]
#  colmap_dir: "C:/DATASET/Test_imgs2_colmap_neural/sparse_align"
  colmap_dir: "d:/Projects/NeuralRecon/Test_data/OBL_L7/Test_imgs2_colmap_neural/sparse_align"
  img_size: [600,400]
  num_sample: 1e8
  resample_after_n_epoches: 100
  target_img: ['6h00277']

trainer:
  check_val_every_n_epoch: 100
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0

#  batch_size: 4096
  batch_size: 24000
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false

  output: output/neural_recon/img_nif_log

model:
  model_name: Image_model

hydra:
  run:
    dir: .
  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled