dataset:
  root: F:\GSP\training

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0

  batch_size: 1
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 10000000

model:
  model_name: Base_model
  phase: 0

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled