dataset:
  root: data/detailed_l7_with_ground.ply
  rebuild_data: false

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0

  batch_size: 4096
  resume_from_checkpoint:
  evaluate: false
  output: .
  check_val_every_n_epoch: 1

model:
  model_name: BSP_base_model
  phase: 0
  pdim: 4096
  cdim: 256

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled