dataset:
  root: G:/Dataset/GSP/GSP_v8_100/training.h5
  dataset_name: ABC_test_voxel
#  test_list: ["G:/Dataset/ABC/quadric_test/00999739/00999739_348b49253ff07a020fc5fe58_trimesh_000.obj"]
  test_list: [
    "G:/Dataset/ABC/quadric_test/00990017/00990017_d770b3b036e65283d9195870_trimesh_002.obj",
    "G:/Dataset/ABC/quadric_test/00990044/00990044_44ff2f0a4e7e92d94d816fe9_trimesh_001.obj",
#    "G:/Dataset/ABC/quadric_test/00990267/00990267_c3a4c16b691d5fa972811080_trimesh_000.obj",
#    "G:/Dataset/ABC/quadric_test/00990271/00990271_e6d9b3822bd5bb0ee58ee10d_trimesh_001.obj",
  ]

trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0

  spawn: false
  num_samples: -1
  batch_size: 128
  resume_from_checkpoint: output/neural_bsp/1017_v9_point_whole.ckpt
  evaluate: true
  output: .
  check_val_every_n_epoch: 1
  accelerator: "16-mixed"

model:
  model_name: PC_model_whole_voxel
  depths: 4
  channels: 7
  need_normalize: false
  voxelize_res: 64

  test_threshold: 0.3
  test_resolution: 256

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d_%H_%M_%S}
  job:
    chdir: False
#  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled