trainer:
  learning_rate: 1e-5
  gpu: 1
  num_worker: 32
#  dataset_name: Regress_hyper_parameters_dataset_with_imgs_with_truncated_error
  dataset_name: Regress_hyper_parameters_dataset_with_imgs
  train_dataset: /mnt/d/reconstructability/training_data/v5/xuexiao_fine_ds_0090/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_fine_ds_0070/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_fine_dp_0090/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_fine_dp_0070/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_fine_sm_0090/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_preview_ds_0090/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_preview_dp_0090/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_preview_dp_0070/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_preview_sm_0070/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_preview_sm_0090/training_data
  valid_dataset: /mnt/d/reconstructability/training_data/v5/xuexiao_fine_sm_0070/training_data*/mnt/d/reconstructability/training_data/v5/xuexiao_preview_ds_0070/training_data
  test_dataset: D:\Projects\Reconstructability\pre_computed\ds_fine_trajectory_fine_proxy_school\training_data
  loss: loss_l2_recon

  batch_size: 128
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
  running_sanity_check: false

model:
  model_name: Uncertainty_Modeling_wo_pointnet7
  involve_img: false
  open_weights: true
  num_points_per_batch: 256
  view_mean_std: [0.2396,0.0206,1.3202,0.6542,0.4880,0.8267,1.4230,0.6673,0.2400,0.4130]
  error_mean_std: [0.0170,0.0383,0.0638,0.2221]

hydra:
  run:
    dir: .
  output_subdir: null
